services:
  - type: web
    name: tareas-laravel
    env: docker
    plan: starter
    branch: main
    region: oregon
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    port: 80
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://tareas-laravel.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: tareas-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: tareas-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: tareas-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: tareas-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: tareas-db
          property: password

databases:
  - name: tareas-db
    plan: free
