services:
  - type: web
    name: tareas-laravel
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: tareas-db
          property: host
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        fromDatabase:
          name: tareas-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: tareas-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: tareas-db
          property: password
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: 120

databases:
  - name: tareas-db
    plan: free
    region: oregon
