services:
  - type: web
    name: tareas-1
    env: docker
    plan: free
    branch: main
    region: oregon
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://tareas-1-5g03.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: bcpv4sjzvhlcd5zqd0iu-postgresql.services.clever-cloud.com
      - key: DB_PORT
        value: 50013
      - key: DB_DATABASE
        value: bcpv4sjzvhlcd5zqd0iu
      - key: DB_USERNAME
        value: u6epudwkd89b0axbmtoa
      - key: DB_PASSWORD
        value: mkeg3lBjxnSWXIhErX717BCW07RvZH
services:
  - type: web
    name: tareas-1
    env: docker
    plan: free
    branch: main
    region: oregon
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://tareas-1-5g03.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: bcpv4sjzvhlcd5zqd0iu-postgresql.services.clever-cloud.com
      - key: DB_PORT
        value: 50013
      - key: DB_DATABASE
        value: bcpv4sjzvhlcd5zqd0iu
      - key: DB_USERNAME
        value: u6epudwkd89b0axbmtoa
      - key: DB_PASSWORD
        value: mkeg3lBjxnSWXIhErX717BCW07RvZH
