services:
  - type: web
    name: tareas
    env: docker
    branch: main
    plan: starter
    region: oregon
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:lQl5xuB3n+Pzp7BZYrF1k5YQ8q96mdrX1MBPG+mnHEg=
      - key: APP_URL
        value: https://tareas-1-5g03.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: bcpv4sjzvhlcd5zqd0iu-postgresql.services.clever-cloud.com
      - key: DB_PORT
        value: "50013"
      - key: DB_DATABASE
        value: bcpv4sjzvhlcd5zqd0iu
      - key: DB_USERNAME
        value: u6epudwkd89b0axbmtoa
      - key: DB_PASSWORD
        value: mkeg3lBjxnSWXIhErX717BCW07RvZH
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
